In [1]:
import pandas as pd
import numpy as np

<h1>NumPy 학습</h1>

1. 파이썬에서 배영을 사용하기 위한 수치 해석용 package
- 적은 메모리로 빠르게 처리 가능한 library
- 다차원 배열 자료 구조 클래스인 ndarray 클래스 지원해서 백터와 행렬을 사용하는 선형대수 계산에 주로 사용
- 배열 연산은 C로 구현된 내부 반복문 사용 --> 순수 파이썬 list 보다 빠름
- 배열 연산을 이용하여 간단한 코드로 복잡한 선형대수 연산 가능

    <img src='img/Dataform_numpy.png' whidth = '70%'>

- Scalar - 순수한 숫자값 의미, 크기만 존재(방향 없음)
- Vector - 뱡향과 크기가 있는 데이터 의미
- Matrix - 2차원 배열
- Tensor - 3차원 이상의 배열


## Numpy 필요성 인지

반복문 실행 시간 비교하기

In [6]:
# test data 구성
numpyArray = np.arange(10000000)
print(type(numpyArray))
print(numpyArray)

<class 'numpy.ndarray'>
[      0       1       2 ... 9999997 9999998 9999999]


In [10]:
# python list 

plist = list(range(10000000))
print(type(plist))


<class 'list'>


In [12]:
plist

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [13]:
%time for _ in range(10): numpyArray = numpyArray * 2
%time for _ in range(10): plist = [x * 2 for x in plist] 

CPU times: user 140 ms, sys: 41.5 ms, total: 182 ms
Wall time: 180 ms
CPU times: user 4.99 s, sys: 1.23 s, total: 6.22 s
Wall time: 6.22 s


## Numpy 모듈을 사용한 1차원 배열 만들기
- array 함수에 리스트를 넣으면 numpy 배열로 변환

In [29]:
data = [0,1,2,3,4,5,6,7,8,9]
print(type(data))
data = np.array(data)
print(type(data))
print(data)

<class 'list'>
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [24]:
#차원 확인
print(data.ndim)
print(data.shape)

1
(10,)


In [25]:
data1 = [[0,1,2,3,4,5,6,7,8,9]]
print(type(data1))
data1 = np.array(data1)
print(type(data1))

<class 'list'>
<class 'numpy.ndarray'>


In [27]:
#차원 확인
print(data1.ndim) 
print(data1.shape)

2
(1, 10)


In [30]:
data = [0,1,2,3,4,5,6,7,8,9]
print(type(data))
data = np.array([data], dtype = 'float')
print(type(data))
print(data)

<class 'list'>
<class 'numpy.ndarray'>
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


## ndarray 의 데이터 타입
- list를 ndarray로 변경 하면 데이터 크키가 더 큰 타입으로 일괄 적용

In [32]:
lst = [1,2,'string']
ndarray = np.array(lst)
print(lst, ndarray)
print(type(lst), type(ndarray))

[1, 2, 'string'] ['1' '2' 'string']
<class 'list'> <class 'numpy.ndarray'>


In [35]:
# 참조: 운영체제가 다른 mac과 구글의 코랩에선 int64와 U21로 표현됨
#결론: os에 따라  타입 사이즈가 소소하게 차이남
# lst = [1,2,'string']
lst = [1,2] # int64 형태 (windows에서 jupyter notebook 사용시 int32로 적용)
ndarray = np.array(lst)
print(lst, ndarray)
print(type(lst), type(ndarray))

print(ndarray.dtype)

[1, 2] [1 2]
<class 'list'> <class 'numpy.ndarray'>
int64


## Numpy 모듈을 사용한 2차원 배열 만들기


In [37]:
data = np.array([[1, 2, 3] ,[4, 5, 6]])
print(data)
print(data.ndim)
print(data.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [38]:
data[0][1]

2

In [41]:
data = np.array([ [[1,2,3,4], 
                  [5,6,7,8], 
                  [9,10,11,12]], 
                  [[21,22,23,24], 
                   [25,26,27,28], 
                   [29,30,31,32]] ])
print(data)
print(data.ndim)
print(data.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]
3
(2, 3, 4)


In [42]:
data[1][2][3] = 47

In [43]:
data

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 47]]])

## ndarray의 차원과 크기를 변경: reshpae()

In [47]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# 5dㅕㄹ로 변경
a2 = a1.reshape(-1,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
a2 = a1.reshape(5,-1)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
a3 = np.arange(9)
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
# 데이터 개수가 홀수 따라서 실행 오류
a33 = a3.reshape(-1,5)

ValueError: cannot reshape array of size 9 into shape (5)

In [55]:
print(a33.ndim)
print(a33.shape)

2
(9, 1)


## Numpy 함수를 사용하여 배열 생성하기

- 규모가 큰 배열의 경우는 Numpy에 내장된 루틴 사용해서 처음부터 배열을 생성하는 것이 효율적
- 주요 함수

--zero(), onse(), empty(), arange(), inspase.....

In [56]:
data = np.zeros(10 , dtype = int)
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
data = np.ones(10 , dtype = int)
data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
data = np.zeros((3,2) , dtype = int)
print(data)
print(data.ndim)
print(data.shape)

[[0 0]
 [0 0]
 [0 0]]
2
(3, 2)


In [60]:
data = np.full((3,2), 5)
data

array([[5, 5],
       [5, 5],
       [5, 5]])

In [61]:
# 0에서 2씩 증가해서 10까지 배열 생성
data = np.arange(0,10,2)
data

array([0, 2, 4, 6, 8])

In [62]:
# 분할 함수
data = np.linspace(0,10,2)
data

array([ 0., 10.])

In [64]:
data = np.linspace(0,10,5)
data

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [65]:
#단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 배열 슬리이싱 과 색인



In [66]:
x = np.arange(10)

In [67]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x[3:5]

array([3, 4])

In [70]:
# 칸 이동수
x[::2]

array([0, 2, 4, 6, 8])

## 데이터 복사하기

1. copy(): 새로운 데이터 생성
- non copy(): 동일한 데이터 활용

In [83]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
y = x[5:8].copy()
y

array([5, 6, 7])

In [85]:
y[0] = 10
y
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
y2 = x[5:8]
y2

array([5, 6, 7])

In [87]:
y2[0] = 15

In [88]:
y2

array([15,  6,  7])

In [79]:
x

array([ 0,  1,  2,  3,  4, 15,  6,  7,  8,  9])

## 배열 결합

1차원 배열 결합

In [89]:
x = np.array([1,2,3])
y = np.array([4,5,6])
(x,y)

(array([1, 2, 3]), array([4, 5, 6]))

In [90]:
d = np.concatenate([x,y])
print(d.ndim)
print(d)
print(d.shape)

1
[1 2 3 4 5 6]
(6,)


2차원 배열간의 결합

In [91]:
x = np.array([[1,2,3],[5,6,7]])
y = np.array([[33,44,55], [11,22,66]])
x,y

(array([[1, 2, 3],
        [5, 6, 7]]),
 array([[33, 44, 55],
        [11, 22, 66]]))

In [94]:
d = np.array([x,y])
print(d.ndim, d.shape)
d

3 (2, 2, 3)


array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[33, 44, 55],
        [11, 22, 66]]])

In [95]:
d = np.concatenate([x,y]) # 차원 변경없이 데이터 값 조합
print(d.ndim, d.shape)
d

2 (4, 3)


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [33, 44, 55],
       [11, 22, 66]])

In [96]:
x

array([[1, 2, 3],
       [5, 6, 7]])

In [97]:
d = np.concatenate([x,y], axis = 0) # 차원 변경없이 데이터 값 조합
print(d.ndim, d.shape)
d

2 (4, 3)


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [33, 44, 55],
       [11, 22, 66]])

In [98]:
d = np.concatenate([x,y], axis = 1) # 차원 변경없이 데이터 값 조합
print(d.ndim, d.shape)
d

2 (2, 6)


array([[ 1,  2,  3, 33, 44, 55],
       [ 5,  6,  7, 11, 22, 66]])

## 전치 연산

1. 2차원 배열의 전치 연산 행과 열을 변경하는 작업
- 표기법 T

In [100]:
x = np.array([[1,2,3],[5,6,7]])
x

array([[1, 2, 3],
       [5, 6, 7]])

In [101]:
y = x.T
y

array([[1, 5],
       [2, 6],
       [3, 7]])

In [102]:
x.ndim, x.shape


(2, (2, 3))

In [103]:
y.ndim, y.shape

(2, (3, 2))

## 벡터의 연산

In [105]:
data = [1,2,3,4,5]
# 2로 곱한 결과 값을 list에 새로 저장

In [106]:
result = []
for v in data :
    result.append(v *2)
result

[2, 4, 6, 8, 10]

In [108]:
# numpy로 구성후 동일한 결과값 출력해 보기
data1 = np.array(data)

data1 * 2

array([ 2,  4,  6,  8, 10])

<!-- Navigation-->
<[Numpy 학습](step08_NumpyFun_Operation.ipynb)>