## 난수 발생과 카운팅

1.seed : 씨앗(기준)
- 필요성 : 향후 머신러닝/딥러닝 개발시에 정확한 예측에 가까운 패텅을 찾으려면 엄청나게 많은 다양한 경우의 수로 학습을 시켜야함
        학습시, 다양한 수치값들도 필요, 일일이 수치값 선정이 불가
- 해결책 : 난수 발생으로 학습을 유도, 단 난수라는 정해진 범위내에서 알수 없는 수들 의미
- 상식: 난수를 발생하는 컴퓨터는 기준이 존재, 개발자들도 그 기준점을 정해서 다수의 사람들이 동일한 난수값을 활용 가능

In [3]:
import numpy as np

In [11]:
np.random.rand(5)

array([0.77648469, 0.14849424, 0.6597844 , 0.07442291, 0.15350714])

In [54]:
np.random.seed(42)


In [56]:
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [85]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])