In [1]:
import numpy as np

<img src='img/유니버설함수.png' withd= '60%'>

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
#난수 발생해서 요소가 3개인 정수값으로 1차원배열 생성
x = np.random.randint(100, 999, size =3)
x

array([426, 384, 499])

In [50]:
y = np.random.randint(100, 999, size =3)
y

array([183, 475, 505])

In [52]:
np.maximum(x,y)

array([426, 475, 505])

## 연산

In [55]:
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
data = np.arange(12).reshape(3,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
data * data

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [58]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
data = np.dot(data, data.T)
data

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

## 차원 축소 연산(집계)

In [62]:
x = np. array([1,2,10,3,4,20])
x

array([ 1,  2, 10,  3,  4, 20])

In [63]:
type(x)

numpy.ndarray

In [64]:
x.sum()

40

In [65]:
x.max()

20

In [66]:
#최대값의 인덱스 값 반환
x.argmax()

5

In [86]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
print(a)
print(a.ndim)
print(a.shape)

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]
2
(3, 4)


In [82]:
b = np.sort(a, axis = 1) # 각 행별로 열을 기준으로 오름차순 정렬
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [83]:
b = np.sort(a, axis = 0)# 각 열별로 행을 기준으로 오름차순 정렬
b

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])