## 1번. random메소드를 사용하되 어려번 실행되어도 같은 값이 나오는 (10,) 형태의 numpy array를 만들어 주세요

소문제
1. array 요소의 합, 최댓값, 최댓값일때의 index 번호룰 출력하세요 
- 브로드케스팅 기능을 이용해서 각 값의 크기를 2배 해주세요
- 브로드케스팅을 이용하여 +3 값을 해주세요
- 행렬을 같은 크기의 행렬을 만들어서 두 행렬의 곱을 구하세요(기존의 array와 다르게 값이 계속 바뀌게 만들어주세요)
- 위에서 만든 행열과 기본의 행렬의 np.dot 연산을 진행해 주세요


In [11]:
import numpy as np

# 1번 array 요소의 합, 최댓값, 최댓값일때의 index 번호를 출력하세요
x = np.random.rand(10)

# arr1 = np.array(x)

xmin = np.min(arr1)

xmin_index = np.where(xmin == x)



xmax = np.max(arr1)
xindex = np.argmax(arr1)
xmax_index = np.where(xmax == x)


In [14]:
# 2번 브로드케스팅 기능을 이용해서 각 값의 크기를 2배 해주세요
x* 2

array([0.27974133, 1.78654496, 0.16893113, 0.0837563 , 1.08140858,
       1.96879788, 0.47171977, 0.78568885, 0.89584807, 1.67284326])

In [15]:
# 3번 브로드케스팅을 이용하여 +3 값을 해주세요
x + 3

array([3.13987067, 3.89327248, 3.08446557, 3.04187815, 3.54070429,
       3.98439894, 3.23585989, 3.39284442, 3.44792403, 3.83642163])

In [19]:
# 4번
# 행렬을 같은 크기의 행렬을 만들어서 두 행렬의 곱을 구하세요(기존의 array와 다르게 값이 계속 바뀌게 만들어주세요)

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

d = a*b
print(d)        

[[ 5 12]
 [21 32]]


In [17]:
# 5번 위에서 만든 행열과 기본의 행렬의 np.dot 연산을 진행해 주세요

c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


## 2번

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 형태를

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]) 
       
       와
       
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
       
형태로 변경하세요
      

In [52]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

b = a.reshape(2,-1)

print(b)

c = a.reshape(5,-1)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 3번. 마크다운에 있는 array를 복사하여 다음 문제를 풀어주세요

data = np.array([ [[1,2,3,4], 
                  [5,6,7,8], 
                  [9,10,11,12]], 
                  [[21,22,23,24], 
                   [25,26,27,28], 
                   [29,30,31,32]] ])
에서 

1. 이 베열의 차원, 모양을 출력하세요 
- 26을 뽑아주세요
- 7 을 39로 변경해주세요


In [29]:
#3-1번
data = np.array([ [[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[21,22,23,24], [25,26,27,28], [29,30,31,32]] ])

print(data.ndim)
print(data.shape)

3
(2, 3, 4)


In [35]:
#3-2번 26을 뽑아주세요

data[1,1,1]

26

In [37]:
#3-3번 7 을 39로 변경해주세요

data[0][1][2] = 39


[[[ 1  2  3  4]
  [ 5  6 39  8]
  [ 9 10 11 12]]

 [[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]


## 4번. 마크다운에 있는 array를 복사하여 다음 문제를 풀어주세요


x = np.array([[1,2,3],[5,6,7]])
y = np.array([[33,44,55], [11,22,66]])
x,y

이 두 array를 이용해서 concatenate 와 array 결합(np.array([x,y]))을 출력하고
두 가지 결합 방법의 차이점을 기술하세요

In [53]:
# concatenate

x = np.array([[1,2,3],[5,6,7]]) 
y = np.array([[33,44,55], [11,22,66]])

np.concatenate([x,y]).shape



(4, 3)

In [54]:
# array 결합

(np.array([x,y])).shape

(2, 2, 3)

두 결합 방법의 차이점을 이 마크다운에 설명해주세요

## 5. 마크다운에 있는 array를 복사하여 다음 문제를 풀어주세요

a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

단, a array는 변경이 없어야 합니다.
1. 각 행별로 열을 기준으로 오름차순 정렬
- 각 열별로 행을 기준으로 오름차순 정렬

In [56]:
# a array 출력
a = np.array([[4, 3, 5, 7], [1, 12, 11, 9], [2, 15, 1, 14]])
print(a)

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]


In [57]:
#각 행별로 열을 기준으로 오름차순 정렬
b = np.sort(a, axis=0)

print(b)

[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]


In [58]:
#각 열별로 행을 기준으로 오름차순 정렬

c = np.sort(a, axis=1)

print(c)

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]


In [59]:
# a array 출력

print(a)

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]
